name: build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - warrenbuckley/Setup-MSBuild@v1
      - run: MSBuild.exe $Env:GITHUB_WORKSPACE\source\GitHubActionsTest\GitHubActionsTest.csproj -p:Configuration=Release

