name: build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: nuget/setup-nuget@v1
      - uses: darenm/Setup-VSTest@v1
      - run: MSBuild.exe $Env:GITHUB_WORKSPACE\source\GitHubActionsTest\GitHubActionsTest.csproj -p:Configuration=Release
      - run: nuget restore $Env:GITHUB_WORKSPACE\source\UnitTest\UnitTest.csproj
      - run: MSBuild.exe $Env:GITHUB_WORKSPACE\source\UnitTest\UnitTest.csproj -p:Configuration=Release
      - run: vstest.console.exe $Env:GITHUB_WORKSPACE\source\UnitTest\bin\Release\UnitTest.dll

